<a href="https://colab.research.google.com/github/ShreyasG27/ML-prac/blob/main/backprop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
def activation_func(Z):
    return 1/(1 + np.exp(-Z))
def deriv_activation(delta, Z):
    S = (Z*(1 - Z))
    S = delta * S
    return S


X = np.array([1, 0, 1])
V1 = np.array([0.3, 0.6, -0.1])
V2 = np.array([0.5, -0.3, 0.4])

Z = np.array([0.0, 0.0, 0.0])

Z[1] = np.dot(V1, X)
Z[2] = np.dot(V2, X)

print('Zin = ', Z)
Z = activation_func(Z)
print('Z = ', Z)

Z[0] = 1
W = np.array([-0.2, 0.4, 0.1])
Y = np.dot(W, Z)
Y = activation_func(Y)
print(Y)

epochs=5

#back propagation
for i in range(epochs):
    error = 1 - Y
    err_op = np.array([0.0, 0.0, 0.0])
    if error != 0:
        learn_rt = 0.25
        err_k = (1-Y)*Y*(1-Y)
        err_in_op = np.dot(W, err_k)
        print(err_in_op)
        err_op[1] = deriv_activation(err_in_op[1], Z[1])
        err_op[2] = deriv_activation(err_in_op[2], Z[2])
        print(err_op)
    
        # new op layer W
        W = np.add(W, np.dot(Z, learn_rt * err_k))
        print('W_new = ', W)
    
        V1 = np.add(V1, np.dot(X, learn_rt *err_op[1]))
        V2 = np.add(V2, np.dot(X, learn_rt *err_op[2]))
        print('V1_new = ',V1)
        print('V2_new = ',V2)

Zin =  [0.  0.2 0.9]
Z =  [0.5       0.549834  0.7109495]
0.5227414361305817
[-0.02381356  0.04762713  0.01190678]
[0.         0.0117885  0.00244685]
W_new =  [-0.17023305  0.41636688  0.1211628 ]
V1_new =  [ 0.30294713  0.6        -0.09705287]
V2_new =  [ 0.50061171 -0.3         0.40061171]
[-0.02026928  0.0495759   0.01442659]
[0.         0.01227086 0.00296467]
W_new =  [-0.14046609  0.43273377  0.1423256 ]
V1_new =  [ 0.30601484  0.6        -0.09398516]
V2_new =  [ 0.50135288 -0.3         0.40135288]
[-0.01672499  0.05152466  0.0169464 ]
[0.         0.01275321 0.00348249]
W_new =  [-0.11069914  0.44910065  0.1634884 ]
V1_new =  [ 0.30920314  0.6        -0.09079686]
V2_new =  [ 0.5022235 -0.3        0.4022235]
[-0.0131807   0.05347343  0.01946621]
[0.         0.01323556 0.00400031]
W_new =  [-0.08093218  0.46546753  0.1846512 ]
V1_new =  [ 0.31251203  0.6        -0.08748797]
V2_new =  [ 0.50322358 -0.3         0.40322358]
[-0.00963642  0.0554222   0.02198602]
[0.         0.01371791 0