<a href="https://colab.research.google.com/github/ShreyasG27/ML-prac/blob/main/perceptronlearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import matplotlib.pyplot as plt
import numpy as np

def learn_percep(x , y , alpha , epoch ,threshold):
    w = np.zeros((x.shape[1],1))
    for t in range(epoch):
        for i in range(x.shape[0]):
            yt = np.dot(x[i] , w)
            yt = np.reshape(yt , (1,1))

            if (yt > threshold) :
                yin=1
            elif (yt < (-1*threshold)):
                yin=-1
            else : yin =0;

            #print(yin)
            if (yin != y[i]):
                p = np.transpose(x[i])
                p = np.reshape(p , (x.shape[1],1))
                w = w + alpha*y[i]*p

            #print(w)
    return w

                   
x = np.array([[1 , 1 , 1] , [1 , 0 , 1] , [0 , 1 , 1] , [0 , 0 , 1]])


yor = np.array([1 , 1 , 1 , -1])
yor = np.reshape(yor , (4 , 1))


yand = np.array([1 , -1 , -1 , -1])
yand = np.reshape(yand , (4 , 1))

yandNot = np.array([-1 , 1 , -1 , -1])
yandNot = np.reshape(yandNot , (4 , 1))

epoch = int(input("Enter epoch "))
alpha = float(input("Enter learning rate "))
threshold = float(input("Enter threshold "))

print("input x : ")
print(x)

##OR perceptron
w1 = learn_percep(x , yor , alpha , epoch , threshold)
print("Weights for OR perceptron : ")
print(w1)

##AND perceptron
w2 = learn_percep(x , yand , alpha , epoch , threshold)
print("Weights for AND perceptron : ")
print(w2)

##AND NOT (A.(~B)) perceptron
w3 = learn_percep(x , yandNot , alpha , epoch , threshold)

print("Weights for AND NOT (A.(~B)) perceptron : ")
print(w3)




Enter epoch 5
Enter learning rate 1
Enter threshold 1
input x : 
[[1 1 1]
 [1 0 1]
 [0 1 1]
 [0 0 1]]
Weights for OR perceptron : 
[[ 3.]
 [ 2.]
 [-1.]]
Weights for AND perceptron : 
[[ 1.]
 [ 1.]
 [-4.]]
Weights for AND NOT (A.(~B)) perceptron : 
[[ 3.]
 [-3.]
 [-2.]]
